#setup
RAWDIR: '/media/utlab/DATA_HDD2/student/Nanopore_Metagenomics/CP_Workflow/RawData'
ROOT: '/media/utlab/DATA_HDD2/student/Nanopore_Metagenomics/CP_Workflow/'
runnames: ['Run0', 'Run1', 'Run2', 'Run3', 'Run4']

# for qcat
barcode_kit: 'NBD103/NBD104'

samples: ['01', '03', '06', '07', '10', '11', '12', '13', '14', '15', '17', '18', '19', '20', '21', '22']
sample_dict:
    'Run0':
      '04': '01'
    'Run1':
      '02': '03'
      '03': '13'
    'Run2':
      '04': '06'
      '05': '07'
      '06': '10'
      '07': '14'
    'Run3':
      '08': '11'
      '09': '12'
      '10': '15'
      '11': '17'
      '12': '18'
    'Run4':
      '01': '19'
      '02': '20'
      '03': '21'
      '04': '22'
# Database for tax classification
# if $MINIKRAKEN_DB not in path, give the path to the minikraken databse here. Can also be defined in the Snakefile if preferred.
kraken_db: '$MINIKRAKEN_DB'
centrifuge_db: '/media/utlab/DATA_HDD1/Nanopore_metagenomics/Softwares_for_analysis/centrifuge-1.0.3-beta/p_compressed+h+v'
